Loadable page to main
Anastasia-cod/Saucedemo pull request #3
Opened 2023-05-19 17:05 UTC by Anastasia-cod

Anastasiya Zayats QAC01-onl

This pull request contains test automation framework https://www.saucedemo.com/ with following applied pattern:

1. Loadable Page

I have some difficulties to understanding how that should be with using my Browser code. I tried my best.

to run tests on MAC using .runsettings file use terminal in VS:
dotnet test -s {path to specific runsettings file}

2023-05-21 21:25 UTC, wildpioneer requested changes

2023-05-21 21:25 UTC, wildpioneer commented on Core/bin/Debug/net6.0/Core.deps.json
> +{
папка bin не может быть закомичена - это временные файлы

2023-05-21 21:25 UTC, wildpioneer commented on Core/obj/Core.csproj.nuget.dgspec.json
> +{
Папка obj не должна быть закомичена - потому что является временной

2023-05-21 21:25 UTC, wildpioneer commented on SauceDemo/Builder/UserBuilder.cs
> +    public static class UserBuilder
Данная реализация не является реализацией Builder паттерна

2023-05-21 21:25 UTC, wildpioneer commented on SauceDemo/Page/CheckoutStepOnePage.cs
> +            Browser.Instance.NavigateToUrl("https://www.saucedemo.com/checkout-step-one.html");
Здесь не может быть жесткой прямой ссылки - ссылка должна формироваться основываясь на настройках

2023-05-21 21:25 UTC, wildpioneer commented on SauceDemo/Page/LoginPage.cs
> +            Browser.Instance.NavigateToUrl("https://www.saucedemo.com/");
Для чего этот метод? Ведь он такой же как и OpenPage в этом классе

2023-05-22 05:52 UTC, Anastasia-cod commented on SauceDemo/Page/LoginPage.cs
> +            Browser.Instance.NavigateToUrl("https://www.saucedemo.com/");
Согласна, лишний метод

2023-05-22 18:30 UTC, Anastasia-cod commented on Core/bin/Debug/net6.0/Core.deps.json
> +{
Исправлено - добавила .gitignore и удалила папку из хранилища и отслеживания
git rm --cached -r <имя_директории>
git commit -m "remove имя_директории from repository"
git push

2023-05-22 18:30 UTC, Anastasia-cod commented on Core/obj/Core.csproj.nuget.dgspec.json
> +{
Исправлено - добавила .gitignore и удалила папку из хранилища и отслеживания
git rm --cached -r <имя_директории>
git commit -m "remove имя_директории from repository"
git push

2023-05-22 19:18 UTC, Anastasia-cod commented on SauceDemo/Page/CheckoutStepOnePage.cs
> +            Browser.Instance.NavigateToUrl("https://www.saucedemo.com/checkout-step-one.html");
Исправлено

2023-06-05 17:46 UTC, wildpioneer commented
Проверено

2023-06-05 17:46 UTC, closed without merging